[package]
name = "vcard"
version = "0.1.0"
edition = "2018"

[dependencies]

thiserror= "1"
regex = "1"
lazy_static="1"
strum = { version = "0.22"}
strum_macros = "0.22"
vcard_macro = {path = "../vcard_macro"}
